import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'en' | 'ar' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('preferredLanguage') as Language;
    if (savedLanguage && ['en', 'ar', 'fr'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  useEffect(() => {
    // Update HTML dir attribute and class for RTL support
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.classList.toggle('rtl', language === 'ar');
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('preferredLanguage', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider 
      value={{ 
        language, 
        setLanguage, 
        t, 
        dir: language === 'ar' ? 'rtl' : 'ltr'
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

// Translation object
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'nav.dashboard': 'Dashboard',
    'nav.about': 'About',
    'nav.settings': 'Settings',
    'btn.getStarted': 'Get Started',
    'btn.emergency': 'Emergency',

    // Bottom Navigation
    'nav.home': 'Home',
    'nav.options': 'Options',
    'nav.scenario': 'Scenario',

    // Hero Section
    'hero.title': 'Find the fastest hospital now',
    'hero.subtitle': "We'll compare road ETAs and use live traffic only when the free provider is available.",
    'btn.shareLocation': 'Share my location',
    'hero.loading': 'Calculating available travel-time data…',
    'hero.bestOption': 'Best option',
    'hero.startNavigation': 'Start Navigation',
    'hero.noHospitals': 'No hospitals found nearby. Expand your search radius in Options.',

    // Metrics
    'metrics.eta': 'ETA',
    'metrics.distance': 'km',
    'metrics.lowTraffic': 'Low traffic',
    'metrics.moderateTraffic': 'Moderate traffic',
    'metrics.heavyTraffic': 'Heavy traffic',

    // Emergency Types
    'emergency.general': 'General ER',
    'emergency.cardiac': 'Cardiac',
    'emergency.pediatric': 'Pediatric',
    'emergency.maternity': 'Maternity',

    // Options Page
    'options.title': 'Emergency options',
    'options.subtitle': "Select the care you need, and we'll prioritize those facilities.",
    'options.emergencyType': 'Emergency type',
    'options.searchRadius': 'Search radius (km)',
    'options.updateResults': 'Update results',
    'options.reachableAreas': 'Reachable areas right now',
    'options.legend.5min': '5 min',
    'options.legend.10min': '10 min',
    'options.legend.15min': '15 min',

    // Dashboard
    'dashboard.title': 'Emergency access insights',
    'dashboard.subtitle': 'Average time to reach a hospital, based on recent data',
    'dashboard.avgETA': 'Citywide avg ETA',
    'dashboard.peakHour': 'Peak hour',
    'dashboard.bestHour': 'Best hour',
    'dashboard.noData': 'Data will appear as you use the app or after sample seeding.',
    'dashboard.minutes': 'min',
    'dashboard.hour': 'Hour',
    'dashboard.area': 'Area',
    'dashboard.avgTime': 'Avg Time',

    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Customize your QuickER experience',
    'settings.appearance': 'Appearance',
    'settings.theme': 'Theme',
    'settings.themeDesc': 'Choose your preferred theme appearance',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.system': 'System',
    'settings.language': 'Language',
    'settings.interfaceLanguage': 'Interface Language',
    'settings.languageDesc': 'Choose your preferred language for the app',
    'settings.emergencyPrefs': 'Emergency Preferences',
    'settings.defaultEmergencyType': 'Default Emergency Type',
    'settings.emergencyTypeDesc': 'Pre-select your most common emergency type',
    'settings.privacyData': 'Privacy & Data',
    'settings.analytics': 'Store Local Decision History',
    'settings.analyticsDesc': 'Keep non-location search summaries in this browser for the dashboard',
    'settings.clearCache': 'Clear Cached Data',
    'settings.cacheDesc': 'Remove temporary page sessions, local decision history, and demo availability statuses',
    'settings.exportData': 'Export Your Data',
    'settings.exportDesc': 'Download your current preferences (JSON)',
    'settings.legal': 'Legal & Privacy',
    'settings.aboutApp': 'About QuickER',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.termsOfService': 'Terms of Service',
    'settings.version': 'v1.0.0',
    'settings.tagline': 'Emergency care routing made simple',
    'settings.copyright': '© 2026 QuickER hackathon prototype.',

    // Onboarding
    'onboarding.slide1.title': 'Fastest hospital by ETA',
    'onboarding.slide1.desc': 'Compare nearby hospitals by road travel time, with live traffic only when the free provider is available.',
    'onboarding.slide2.title': 'Emergency filters',
    'onboarding.slide2.desc': 'Filter public hospital metadata by cardiac, pediatric, maternity or general care, then confirm services with the facility.',
    'onboarding.slide3.title': 'Your data & privacy',
    'onboarding.slide3.desc': 'We use your location to compute routes. Precise coordinates stay only in temporary tab memory while you navigate and are cleared on reload or tab close.',
    'onboarding.slide4.title': 'Enable location access',
    'onboarding.slide4.desc': 'Allow location access to find nearby hospitals and calculate accurate routes to emergency care.',
    'onboarding.slide5.title': 'Choose your language',
    'onboarding.slide5.desc': 'Select your preferred language for the best QuickER experience.',
    'onboarding.enableLocation': 'Enable Location',
    'onboarding.locationEnabled': 'Location Enabled',
    'onboarding.selectLanguage': 'Select Language',
    'onboarding.back': 'Back',
    'onboarding.next': 'Next',
    'onboarding.disclaimer': 'This app does not provide medical advice.',
    'onboarding.privacyNotice': 'Precise coordinates stay only in temporary tab memory and are cleared on reload or tab close.',
    'onboarding.medicalDisclaimer': 'Always call emergency services for life-threatening situations.',
    'onboarding.getStarted': 'Get Started',

    // About
    'about.title': 'About QuickER',
    'about.description': 'QuickER compares hospitals using the best available road ETA and clearly labels whether optional live traffic is active. It is not a substitute for professional medical advice or emergency services.',
    'about.warning': 'If you are in immediate danger, call local emergency numbers.',

    // Errors
    'error.permissionDenied': "We can't find your location. Enable location in your browser or choose a custom start point.",
    'error.apiFailure': 'Traffic data unavailable. Showing estimated times.',
    'error.offline': "You're offline. We'll retry automatically.",
    'error.mapFailed': 'Map failed to load. Retry or switch provider.',

    // Toasts
    'toast.themeUpdated': 'Theme updated',
    'toast.themeChanged': 'Theme preference has been saved',
    'toast.languageUpdated': 'Language updated',
    'toast.languageChanged': 'Interface language changed to English.',
    'toast.emergencyTypeUpdated': 'Default emergency type updated',
    'toast.preferenceSaved': 'Your preference has been saved.',
    'toast.analyticsEnabled': 'Analytics enabled',
    'toast.analyticsDisabled': 'Analytics disabled',
    'toast.analyticsEnabledDesc': 'Future decision summaries will be stored only in this browser.',
    'toast.analyticsDisabledDesc': 'Future decision summaries will not be saved.',
    'toast.cacheCleared': 'Cache cleared',
    'toast.cacheClearedDesc': 'Cached data has been removed. Your preferences were preserved.',
    'toast.dataExported': 'Data exported',
    'toast.dataExportedDesc': 'Your anonymized data has been downloaded.',

    // Buttons
    'btn.clearCache': 'Clear Cache',
    'btn.exportData': 'Export Data',
    'btn.apply': 'Apply',

    // About Page
    'about.backToHome': 'Back to Home',
    'about.badge': 'About QuickER',
    'about.heroTitle': 'Emergency care routing made simple',
    'about.heroSubtitle': 'Get to the right hospital, faster. Because in emergencies, minutes matter.',
    'about.whatWeDo': 'What We Do',
    'about.whatWeDoDesc1': 'QuickER compares hospitals using the best available road ETA and clearly labels whether optional live traffic is active. It is not a substitute for professional medical advice or emergency services.',
    'about.whatWeDoDesc2': 'The app compares available road ETAs, public specialty metadata and clearly labelled demo availability statuses.',
    'about.whatWeDoDesc3': 'We aggregate data from multiple sources to ensure you get the most accurate and up-to-date information when every minute counts.',
    'about.disclaimer': 'Important Disclaimer',
    'about.disclaimerTitle': 'If you are in immediate danger or experiencing a life-threatening emergency, call your local emergency number immediately.',
    'about.disclaimerDesc': 'QuickER is a routing assistance tool and does not provide medical advice, diagnosis, or treatment recommendations. Always consult with qualified healthcare professionals for medical decisions.',
    'about.emergencyNumbers': 'Emergency Numbers',
    'about.howItWorks': 'How It Works',
    'about.step1Title': '1. Location Detection',
    'about.step1Desc': 'We use your current location to find nearby emergency facilities',
    'about.step2Title': '2. Real-time Analysis',
    'about.step2Desc': 'We disclose whether each ETA uses live traffic, a road network or a distance estimate',
    'about.step3Title': '3. Optimized Routing',
    'about.step3Desc': 'Get the fastest route to the most appropriate care facility',
    'about.techPartners': 'Technology Partners',
    'about.techPartnersDesc': 'QuickER is powered by industry-leading APIs and services:',
    'about.questionsTitle': 'Questions or Feedback?',
    'about.questionsDesc': 'We\'re committed to improving emergency care access for everyone.',
    'about.viewSettings': 'View Settings',
    'about.contactSupport': 'Contact Support',

    // Dashboard Additional
    'dashboard.neighborhoodTimes': 'Neighborhood Access Times',
    'dashboard.longestTimes': 'Areas with Longest Access Times',
    'dashboard.exportData': 'Export Data',
    'dashboard.generateSample': 'Run Rerouting Demo',
    'dashboard.last7Days': 'Last 7 days',
    'dashboard.avgETAByHour': 'Average ETA by',

    // Emergency Countries
    'emergency.countries.us': 'United States',
    'emergency.countries.uk': 'United Kingdom',
    'emergency.countries.eu': 'European Union',
    'emergency.countries.ca': 'Canada',
    'emergency.countries.au': 'Australia',
    'emergency.services.police': 'Police, Fire, Medical',
    'emergency.services.general': 'Emergency Services',

    // Privacy Policy
    'privacy.backToSettings': 'Back to Settings',
    'privacy.title': 'Privacy Policy',
    'privacy.subtitle': 'Your privacy and data protection with QuickER',
    'privacy.lastUpdated': 'Last updated: July 2026',
    'privacy.introduction.title': 'Introduction',
    'privacy.introduction.desc1': 'At QuickER, we are committed to protecting your privacy while providing essential emergency routing services. This Privacy Policy explains how we collect, use, and protect your information.',
    'privacy.introduction.desc2': 'We believe transparency is crucial, especially when dealing with sensitive location data during emergency situations.',
    'privacy.dataCollection.title': 'Information We Collect',
    'privacy.dataCollection.location.title': 'Location Information',
    'privacy.dataCollection.location.desc': 'We collect your location data to provide routing services:',
    'privacy.dataCollection.location.item1': 'Current GPS coordinates (only when you grant permission)',
    'privacy.dataCollection.location.item2': 'Approximate location for traffic and routing calculations',
    'privacy.dataCollection.location.item3': 'Route preferences and destination selections',
    'privacy.dataCollection.usage.title': 'Usage Analytics',
    'privacy.dataCollection.usage.desc': 'When local history is enabled, this browser stores:',
    'privacy.dataCollection.usage.item1': 'Search time, emergency filter, and candidate count',
    'privacy.dataCollection.usage.item2': 'Recommended facility, ETA, and disclosed ETA source',
    'privacy.dataCollection.usage.item3': 'Demo availability status; precise coordinates are excluded',
    'privacy.dataCollection.preferences.title': 'App Preferences',
    'privacy.dataCollection.preferences.desc': 'We store your settings locally on your device:',
    'privacy.dataCollection.preferences.item1': 'Language preferences and emergency type defaults',
    'privacy.dataCollection.preferences.item2': 'Search radius and notification preferences',
    'privacy.dataCollection.preferences.item3': 'Analytics opt-in/opt-out status',
    'privacy.dataUse.title': 'How We Use Your Information',
    'privacy.dataUse.item1': 'Calculate routes using available live-traffic or road-network estimates',
    'privacy.dataUse.item2': 'Provide estimated arrival times and turn-by-turn navigation',
    'privacy.dataUse.item3': 'Build the dashboard from summaries stored only in this browser',
    'privacy.dataUse.item4': 'Remember your preferences for emergency types and search settings',
    'privacy.dataUse.item5': 'Generate insights about emergency care accessibility in different areas',
    'privacy.location.title': 'Location Data & Privacy',
    'privacy.location.important.title': 'Important: Precise Coordinates Are Not Persistently Stored',
    'privacy.location.important.desc': 'QuickER keeps precise coordinates only in temporary tab memory so your page results survive navigation. They disappear on reload or tab close and are sent to the map and routing providers needed to answer your request.',
    'privacy.location.desc1': 'Your location is used to discover hospitals, calculate routes, and draw optional isochrones. It is not included in QuickER decision history.',
    'privacy.location.desc2': 'Location is processed in your browser, retained temporarily while this tab is open, and sent directly to map or routing providers only when needed. This version does not build a server-side movement history.',
    'privacy.location.controls.title': 'You Control Your Location Data:',
    'privacy.location.controls.item1': 'Grant or deny location access through your browser settings',
    'privacy.location.controls.item2': 'Clear temporary page and cached data through the app settings',
    'privacy.location.controls.item3': 'Disable location sharing entirely (though this limits functionality)',
    'privacy.sharing.title': 'Data Sharing & Third Parties',
    'privacy.sharing.desc': 'We minimize data sharing and only work with trusted partners for essential services:',
    'privacy.sharing.thirdParty.title': 'Third-Party Services:',
    'privacy.sharing.thirdParty.item1': 'Map and routing providers (for navigation calculations)',
    'privacy.sharing.thirdParty.item2': 'Cloudflare Pages Functions (optional secret-protecting provider proxy)',
    'privacy.sharing.thirdParty.item3': 'The optional AI explanation runs on-device; only model files are downloaded and the decision summary stays in your browser',
    'privacy.sharing.emergency.title': 'Emergency Situations:',
    'privacy.sharing.emergency.desc': 'This version does not send location history to emergency services or research partners.',
    'privacy.rights.title': 'Your Rights & Control',
    'privacy.rights.access.title': 'Access Your Data',
    'privacy.rights.access.desc': 'View local decision history in the dashboard',
    'privacy.rights.export.title': 'Export Your Data',
    'privacy.rights.export.desc': 'Download preferences as JSON and local decision history as CSV',
    'privacy.rights.delete.title': 'Delete Your Data',
    'privacy.rights.delete.desc': 'Clear all cached data and reset your preferences',
    'privacy.rights.analytics.title': 'Control Analytics',
    'privacy.rights.analytics.desc': 'Enable or disable future local decision-history storage',
    'privacy.security.title': 'Security Measures',
    'privacy.security.desc': 'QuickER minimizes stored data and keeps provider secrets out of the browser bundle:',
    'privacy.security.encryption.title': 'Data Encryption',
    'privacy.security.encryption.desc': 'All data transmission is encrypted using HTTPS/TLS protocols',
    'privacy.security.storage.title': 'Secure Storage',
    'privacy.security.storage.desc': 'Preferences and summaries use browser localStorage; precise coordinates use temporary tab memory only. Local browser data is not encrypted by QuickER',
    'privacy.updates.title': 'Policy Updates',
    'privacy.updates.desc': 'We may update this Privacy Policy to reflect changes in our practices or legal requirements. We will notify users of significant changes through the app.',
    'privacy.contact.title': 'Contact Us',
    'privacy.contact.desc': 'If you have questions about this Privacy Policy or your data:',
    'privacy.contact.email': 'Email:',
    'privacy.contact.address': 'Project contact:',
    'privacy.contact.addressLine': 'Use the public GitHub repository or hackathon submission contact.',
    'privacy.footer': '© 2026 QuickER hackathon prototype.',

    // Terms of Service
    'terms.backToSettings': 'Back to Settings',
    'terms.title': 'Terms of Service',
    'terms.lastUpdated': 'Last updated:',
    'terms.acceptance.title': '1. Acceptance of Terms',
    'terms.acceptance.desc1': 'By accessing and using QuickER ("the App"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.',
    'terms.acceptance.desc2': 'QuickER is an emergency healthcare location service designed to help users find nearby hospitals and emergency services. This application is not a substitute for professional medical advice, diagnosis, or treatment.',
    'terms.medical.title': '2. Medical Disclaimer',
    'terms.medical.important': 'IMPORTANT MEDICAL DISCLAIMER:',
    'terms.medical.disclaimer': 'QuickER is NOT a medical service and does not provide medical advice. In an emergency, contact your local emergency services immediately. Do not rely solely on this app for emergency care.',
    'terms.medical.desc': 'The information provided by QuickER is for informational purposes only and should not be considered as medical advice, diagnosis, or treatment recommendations. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.',
    'terms.license.title': '3. Use License',
    'terms.license.desc': 'Permission is granted to temporarily download one copy of QuickER for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:',
    'terms.license.item1': 'modify or copy the materials',
    'terms.license.item2': 'use the materials for any commercial purpose or for any public display',
    'terms.license.item3': 'attempt to reverse engineer any software contained in the app',
    'terms.license.item4': 'remove any copyright or other proprietary notations from the materials',
    'terms.responsibilities.title': '4. User Responsibilities',
    'terms.responsibilities.desc': 'By using QuickER, you agree to:',
    'terms.responsibilities.item1': 'Use the app only for lawful purposes and in accordance with these Terms',
    'terms.responsibilities.item2': 'Provide accurate location information when using emergency services',
    'terms.responsibilities.item3': 'Not interfere with or disrupt the app\'s functionality',
    'terms.responsibilities.item4': 'Not use the app to transmit harmful, offensive, or illegal content',
    'terms.responsibilities.item5': 'Understand that location data may not always be 100% accurate',
    'terms.privacy.title': '5. Privacy and Data Collection',
    'terms.privacy.desc': 'Your privacy is important to us. QuickER may collect:',
    'terms.privacy.item1': 'Location data to provide nearby hospital information',
    'terms.privacy.item2': 'Usage analytics to improve app performance (if opted in)',
    'terms.privacy.item3': 'Preferences and settings data',
    'terms.privacy.policy': 'For detailed information about how we collect, use, and protect your data, please review our',
    'terms.availability.title': '6. Service Availability',
    'terms.availability.desc': 'QuickER strives to provide accurate and up-to-date information about healthcare facilities. However, we cannot guarantee:',
    'terms.availability.item1': '100% accuracy of hospital locations or contact information',
    'terms.availability.item2': 'Real-time availability of medical services',
    'terms.availability.item3': 'Continuous app availability without interruptions',
    'terms.availability.item4': 'That all hospitals will accept your insurance or provide specific treatments',
    'terms.liability.title': '7. Limitation of Liability',
    'terms.liability.desc': 'In no event shall QuickER or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use QuickER, even if QuickER or its authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.',
    'terms.modifications.title': '8. Modifications to Terms',
    'terms.modifications.desc': 'QuickER may revise these terms of service at any time without notice. By using this app, you are agreeing to be bound by the then current version of these terms of service. Continued use of the app after changes are posted constitutes acceptance of the modified terms.',
    'terms.governing.title': '9. Governing Law',
    'terms.governing.desc': 'These terms and conditions are governed by and construed in accordance with applicable local laws, and you irrevocably submit to the exclusive jurisdiction of the courts in that state or location.',
    'terms.contact.title': '10. Contact Information',
    'terms.contact.desc': 'If you have any questions about these Terms of Service, please contact us through the app\'s',
    'terms.contact.about': 'About page',
    'terms.contact.effective': 'These terms are effective as of the date last updated above and will remain in effect except with respect to any changes in their provisions in the future, which will be in effect immediately after being posted on this page.',
    'terms.returnToSettings': 'Return to Settings'
  },
  ar: {
    // Header
    'nav.dashboard': 'لوحة التحكم',
    'nav.about': 'حول التطبيق',
    'nav.settings': 'الإعدادات',
    'btn.getStarted': 'ابدأ الآن',
    'btn.emergency': 'طوارئ',

    // Bottom Navigation
    'nav.home': 'الرئيسية',
    'nav.options': 'الخيارات',
    'nav.scenario': 'المحاكاة',

    // Hero Section
    'hero.title': 'اعثر على أسرع مستشفى الآن',
    'hero.subtitle': 'سنقارن أوقات الطريق ونستخدم حركة المرور المباشرة فقط عند توفر المزود المجاني.',
    'btn.shareLocation': 'شارك موقعي',
    'hero.loading': 'حساب بيانات وقت السفر المتاحة...',
    'hero.bestOption': 'أفضل خيار',
    'hero.startNavigation': 'ابدأ التنقل',
    'hero.noHospitals': 'لم يتم العثور على مستشفيات قريبة. وسّع نطاق البحث في الخيارات.',

    // Metrics
    'metrics.eta': 'وقت الوصول',
    'metrics.distance': 'كم',
    'metrics.lowTraffic': 'حركة مرور خفيفة',
    'metrics.moderateTraffic': 'حركة مرور متوسطة',
    'metrics.heavyTraffic': 'حركة مرور كثيفة',

    // Emergency Types
    'emergency.general': 'طوارئ عامة',
    'emergency.cardiac': 'قلبية',
    'emergency.pediatric': 'أطفال',
    'emergency.maternity': 'ولادة',

    // Options Page
    'options.title': 'خيارات الطوارئ',
    'options.subtitle': 'اختر نوع الرعاية التي تحتاجها، وسنعطي الأولوية لتلك المرافق.',
    'options.emergencyType': 'نوع الطوارئ',
    'options.searchRadius': 'نطاق البحث (كم)',
    'options.updateResults': 'تحديث النتائج',
    'options.reachableAreas': 'المناطق القابلة للوصول الآن',
    'options.legend.5min': '٥ دقائق',
    'options.legend.10min': '١٠ دقائق',
    'options.legend.15min': '١٥ دقيقة',

    // Dashboard
    'dashboard.title': 'رؤى الوصول للطوارئ',
    'dashboard.subtitle': 'متوسط الوقت للوصول إلى المستشفى، بناءً على البيانات الحديثة',
    'dashboard.avgETA': 'متوسط وقت الوصول بالمدينة',
    'dashboard.peakHour': 'ساعة الذروة',
    'dashboard.bestHour': 'أفضل ساعة',
    'dashboard.noData': 'ستظهر البيانات عند استخدامك للتطبيق أو بعد ملء البيانات التجريبية.',
    'dashboard.minutes': 'دقيقة',
    'dashboard.hour': 'الساعة',
    'dashboard.area': 'المنطقة',
    'dashboard.avgTime': 'متوسط الوقت',

    // Settings
    'settings.title': 'الإعدادات',
    'settings.subtitle': 'خصص تجربتك مع QuickER',
    'settings.appearance': 'المظهر',
    'settings.theme': 'السمة',
    'settings.themeDesc': 'اختر مظهر السمة المفضل لديك',
    'settings.light': 'فاتح',
    'settings.dark': 'داكن',
    'settings.system': 'النظام',
    'settings.language': 'اللغة',
    'settings.interfaceLanguage': 'لغة الواجهة',
    'settings.languageDesc': 'اختر لغتك المفضلة للتطبيق',
    'settings.emergencyPrefs': 'تفضيلات الطوارئ',
    'settings.defaultEmergencyType': 'نوع الطوارئ الافتراضي',
    'settings.emergencyTypeDesc': 'اختر مسبقاً نوع الطوارئ الأكثر شيوعاً',
    'settings.privacyData': 'الخصوصية والبيانات',
    'settings.analytics': 'حفظ سجل القرارات محلياً',
    'settings.analyticsDesc': 'حفظ ملخصات البحث دون الموقع في هذا المتصفح للوحة المعلومات',
    'settings.clearCache': 'مسح البيانات المخزنة مؤقتاً',
    'settings.cacheDesc': 'حذف جلسات الصفحات المؤقتة وسجل القرارات المحلي وحالات التوفر التجريبية',
    'settings.exportData': 'تصدير بياناتك',
    'settings.exportDesc': 'تحميل التفضيلات الحالية (JSON)',
    'settings.legal': 'القانونية والخصوصية',
    'settings.aboutApp': 'حول QuickER',
    'settings.privacyPolicy': 'سياسة الخصوصية',
    'settings.termsOfService': 'شروط الخدمة',
    'settings.version': 'الإصدار ١.٠.٠',
    'settings.tagline': 'توجيه رعاية الطوارئ بسهولة',
    'settings.copyright': '© ٢٠٢٦ نموذج QuickER للهاكاثون.',

    // Onboarding
    'onboarding.slide1.title': 'أسرع مستشفى حسب وقت الوصول',
    'onboarding.slide1.desc': 'قارن المستشفيات القريبة حسب وقت الطريق، مع استخدام المرور المباشر فقط عند توفر المزود المجاني.',
    'onboarding.slide2.title': 'مرشحات الطوارئ',
    'onboarding.slide2.desc': 'رشح بيانات المستشفيات العامة حسب النوع ثم أكد الخدمة المطلوبة مباشرة مع المستشفى.',
    'onboarding.slide3.title': 'بياناتك وخصوصيتك',
    'onboarding.slide3.desc': 'نستخدم موقعك لحساب الطرق. تبقى الإحداثيات الدقيقة فقط في ذاكرة مؤقتة داخل علامة التبويب أثناء التنقل، وتُمسح عند إعادة التحميل أو إغلاق علامة التبويب.',
    'onboarding.slide4.title': 'تمكين الوصول للموقع',
    'onboarding.slide4.desc': 'اسمح بالوصول للموقع للعثور على المستشفيات القريبة وحساب طرق دقيقة للرعاية الطارئة.',
    'onboarding.slide5.title': 'اختر لغتك',
    'onboarding.slide5.desc': 'اختر لغتك المفضلة للحصول على أفضل تجربة QuickER.',
    'onboarding.enableLocation': 'تمكين الموقع',
    'onboarding.locationEnabled': 'تم تمكين الموقع',
    'onboarding.selectLanguage': 'اختر اللغة',
    'onboarding.back': 'رجوع',
    'onboarding.next': 'التالي',
    'onboarding.disclaimer': 'هذا التطبيق لا يقدم نصائح طبية.',
    'onboarding.privacyNotice': 'تبقى الإحداثيات الدقيقة فقط في ذاكرة مؤقتة داخل علامة التبويب، وتُمسح عند إعادة التحميل أو إغلاق علامة التبويب.',
    'onboarding.medicalDisclaimer': 'اتصل دائماً بخدمات الطوارئ في الحالات المهددة للحياة.',
    'onboarding.getStarted': 'ابدأ الآن',

    // About
    'about.title': 'حول QuickER',
    'about.description': 'يقارن QuickER المستشفيات باستخدام أفضل وقت وصول متاح عبر الطرق، ويوضح بجلاء ما إذا كانت بيانات المرور المباشر الاختيارية فعالة. وهو ليس بديلاً عن المشورة الطبية أو خدمات الطوارئ.',
    'about.warning': 'إذا كنت في خطر مباشر، اتصل بأرقام الطوارئ المحلية.',

    // Errors
    'error.permissionDenied': 'لا يمكننا العثور على موقعك. مكّن الموقع في متصفحك أو اختر نقطة بداية مخصصة.',
    'error.apiFailure': 'بيانات المرور غير متاحة. عرض الأوقات المقدرة.',
    'error.offline': 'أنت غير متصل. سنعيد المحاولة تلقائياً.',
    'error.mapFailed': 'فشل تحميل الخريطة. أعد المحاولة أو غيّر المزود.',

    // Toasts
    'toast.themeUpdated': 'تم تحديث السمة',
    'toast.themeChanged': 'تم حفظ تفضيل السمة',
    'toast.languageUpdated': 'تم تحديث اللغة',
    'toast.languageChanged': 'تم تغيير لغة الواجهة إلى العربية.',
    'toast.emergencyTypeUpdated': 'تم تحديث نوع الطوارئ الافتراضي',
    'toast.preferenceSaved': 'تم حفظ تفضيلك.',
    'toast.analyticsEnabled': 'تم تمكين التحليلات',
    'toast.analyticsDisabled': 'تم تعطيل التحليلات',
    'toast.analyticsEnabledDesc': 'ستُحفظ ملخصات القرارات القادمة في هذا المتصفح فقط.',
    'toast.analyticsDisabledDesc': 'لن تُحفظ ملخصات القرارات القادمة.',
    'toast.cacheCleared': 'تم مسح الذاكرة المؤقتة',
    'toast.cacheClearedDesc': 'تمت إزالة البيانات المخزنة مؤقتاً. تم الحفاظ على تفضيلاتك.',
    'toast.dataExported': 'تم تصدير البيانات',
    'toast.dataExportedDesc': 'تم تحميل بياناتك المجهولة.',

    // Buttons
    'btn.clearCache': 'مسح الذاكرة المؤقتة',
    'btn.exportData': 'تصدير البيانات',
    'btn.apply': 'تطبيق',

    // About Page
    'about.backToHome': 'العودة للرئيسية',
    'about.badge': 'حول QuickER',
    'about.heroTitle': 'توجيه رعاية الطوارئ بسهولة',
    'about.heroSubtitle': 'اوصل إلى المستشفى المناسب، بسرعة أكبر. لأنه في حالات الطوارئ، كل دقيقة مهمة.',
    'about.whatWeDo': 'ما نقوم به',
    'about.whatWeDoDesc1': 'يقارن QuickER المستشفيات باستخدام أفضل وقت وصول متاح عبر الطرق، ويوضح بجلاء ما إذا كانت بيانات المرور المباشر الاختيارية فعالة. وهو ليس بديلاً عن المشورة الطبية أو خدمات الطوارئ.',
    'about.whatWeDoDesc2': 'يقارن التطبيق أوقات الطريق المتاحة وبيانات التخصص العامة وحالات التوفر التجريبية المعلّمة بوضوح.',
    'about.whatWeDoDesc3': 'نجمع البيانات من مصادر متعددة لضمان حصولك على أدق المعلومات وأحدثها عندما تكون كل دقيقة مهمة.',
    'about.disclaimer': 'إخلاء مسؤولية مهم',
    'about.disclaimerTitle': 'إذا كنت في خطر مباشر أو تواجه حالة طوارئ تهدد الحياة، اتصل برقم الطوارئ المحلي فوراً.',
    'about.disclaimerDesc': 'QuickER هو أداة مساعدة في التوجيه ولا يقدم نصائح طبية أو تشخيصاً أو توصيات علاجية. استشر دائماً المختصين الطبيين المؤهلين للقرارات الطبية.',
    'about.emergencyNumbers': 'أرقام الطوارئ',
    'about.howItWorks': 'كيف يعمل',
    'about.step1Title': '١. تحديد الموقع',
    'about.step1Desc': 'نستخدم موقعك الحالي للعثور على مرافق الطوارئ القريبة',
    'about.step2Title': '٢. التحليل الفوري',
    'about.step2Desc': 'نوضح ما إذا كان وقت الوصول يعتمد على مرور مباشر أو شبكة طرق أو تقدير مسافة',
    'about.step3Title': '٣. التوجيه المحسن',
    'about.step3Desc': 'احصل على أسرع طريق إلى مرفق الرعاية الأنسب',
    'about.techPartners': 'الشركاء التقنيون',
    'about.techPartnersDesc': 'QuickER مدعوم بواجهات برمجة التطبيقات والخدمات الرائدة في الصناعة:',
    'about.questionsTitle': 'أسئلة أو ملاحظات؟',
    'about.questionsDesc': 'نحن ملتزمون بتحسين الوصول لرعاية الطوارئ للجميع.',
    'about.viewSettings': 'عرض الإعدادات',
    'about.contactSupport': 'تواصل مع الدعم',

    // Dashboard Additional
    'dashboard.neighborhoodTimes': 'أوقات الوصول للأحياء',
    'dashboard.longestTimes': 'المناطق ذات أطول أوقات الوصول',
    'dashboard.exportData': 'تصدير البيانات',
    'dashboard.generateSample': 'تشغيل عرض إعادة التوجيه',
    'dashboard.last7Days': 'آخر ٧ أيام',
    'dashboard.avgETAByHour': 'متوسط وقت الوصول حسب',

    // Emergency Countries
    'emergency.countries.us': 'الولايات المتحدة',
    'emergency.countries.uk': 'المملكة المتحدة',
    'emergency.countries.eu': 'الاتحاد الأوروبي',
    'emergency.countries.ca': 'كندا',
    'emergency.countries.au': 'أستراليا',
    'emergency.services.police': 'الشرطة، الإطفاء، الطبية',
    'emergency.services.general': 'خدمات الطوارئ',

    // Privacy Policy
    'privacy.backToSettings': 'العودة إلى الإعدادات',
    'privacy.title': 'سياسة الخصوصية',
    'privacy.subtitle': 'خصوصيتك وحماية البيانات مع QuickER',
    'privacy.lastUpdated': 'آخر تحديث: يوليو ٢٠٢٦',
    'privacy.introduction.title': 'مقدمة',
    'privacy.introduction.desc1': 'في QuickER، نحن ملتزمون بحماية خصوصيتك أثناء تقديم خدمات التوجيه الطارئة الأساسية. تشرح سياسة الخصوصية هذه كيف نجمع ونستخدم ونحمي معلوماتك.',
    'privacy.introduction.desc2': 'نؤمن بأن الشفافية أمر بالغ الأهمية، خاصة عند التعامل مع بيانات الموقع الحساسة أثناء حالات الطوارئ.',
    'privacy.dataCollection.title': 'المعلومات التي نجمعها',
    'privacy.dataCollection.location.title': 'معلومات الموقع',
    'privacy.dataCollection.location.desc': 'نجمع بيانات موقعك لتقديم خدمات التوجيه:',
    'privacy.dataCollection.location.item1': 'إحداثيات GPS الحالية (فقط عندما تمنح الإذن)',
    'privacy.dataCollection.location.item2': 'الموقع التقريبي لحسابات المرور والتوجيه',
    'privacy.dataCollection.location.item3': 'تفضيلات الطريق واختيارات الوجهة',
    'privacy.dataCollection.usage.title': 'تحليلات الاستخدام',
    'privacy.dataCollection.usage.desc': 'عند تمكين السجل المحلي، يحفظ هذا المتصفح:',
    'privacy.dataCollection.usage.item1': 'وقت البحث ونوع الطوارئ وعدد المرشحين',
    'privacy.dataCollection.usage.item2': 'المرفق المقترح ووقت الوصول ومصدره المعلن',
    'privacy.dataCollection.usage.item3': 'حالة التوفر التجريبية دون الإحداثيات الدقيقة',
    'privacy.dataCollection.preferences.title': 'تفضيلات التطبيق',
    'privacy.dataCollection.preferences.desc': 'نخزن إعداداتك محلياً على جهازك:',
    'privacy.dataCollection.preferences.item1': 'تفضيلات اللغة وافتراضيات نوع الطوارئ',
    'privacy.dataCollection.preferences.item2': 'نطاق البحث وتفضيلات الإشعارات',
    'privacy.dataCollection.preferences.item3': 'حالة الاشتراك/إلغاء الاشتراك في التحليلات',
    'privacy.dataUse.title': 'كيف نستخدم معلوماتك',
    'privacy.dataUse.item1': 'حساب الطرق باستخدام المرور المباشر المتاح أو تقديرات شبكة الطرق',
    'privacy.dataUse.item2': 'توفير أوقات الوصول المقدرة والتنقل خطوة بخطوة',
    'privacy.dataUse.item3': 'إنشاء لوحة المعلومات من ملخصات محفوظة في هذا المتصفح فقط',
    'privacy.dataUse.item4': 'تذكر تفضيلاتك لأنواع الطوارئ وإعدادات البحث',
    'privacy.dataUse.item5': 'إنشاء رؤى حول إمكانية الوصول للرعاية الطارئة في مناطق مختلفة',
    'privacy.location.title': 'بيانات الموقع والخصوصية',
    'privacy.location.important.title': 'مهم: لا تُخزّن الإحداثيات الدقيقة بشكل دائم',
    'privacy.location.important.desc': 'يحتفظ QuickER بالإحداثيات الدقيقة فقط في ذاكرة مؤقتة داخل علامة التبويب كي تبقى نتائج الصفحة أثناء التنقل. تختفي عند إعادة التحميل أو إغلاق علامة التبويب، وتُرسل إلى مزودي الخرائط والتوجيه اللازمين لتنفيذ طلبك.',
    'privacy.location.desc1': 'يُستخدم موقعك لاكتشاف المستشفيات وحساب الطرق ورسم نطاقات الوصول الاختيارية، ولا يُضاف إلى سجل قرارات QuickER.',
    'privacy.location.desc2': 'تتم معالجة الموقع في متصفحك والاحتفاظ به مؤقتاً ما دامت علامة التبويب مفتوحة، وإرساله مباشرة إلى مزودي الخرائط أو التوجيه عند الحاجة فقط. لا ينشئ هذا الإصدار سجلاً للحركة على الخادم.',
    'privacy.location.controls.title': 'أنت تتحكم في بيانات موقعك:',
    'privacy.location.controls.item1': 'منح أو رفض الوصول للموقع من خلال إعدادات متصفحك',
    'privacy.location.controls.item2': 'مسح بيانات الصفحات المؤقتة والبيانات المخزنة مؤقتاً من خلال إعدادات التطبيق',
    'privacy.location.controls.item3': 'تعطيل مشاركة الموقع بالكامل (مع أن هذا يحد من الوظائف)',
    'privacy.sharing.title': 'مشاركة البيانات والأطراف الثالثة',
    'privacy.sharing.desc': 'نقلل من مشاركة البيانات ونعمل فقط مع شركاء موثوقين للخدمات الأساسية:',
    'privacy.sharing.thirdParty.title': 'خدمات الأطراف الثالثة:',
    'privacy.sharing.thirdParty.item1': 'مقدمو الخرائط والتوجيه (لحسابات التنقل)',
    'privacy.sharing.thirdParty.item2': 'وظائف Cloudflare Pages الاختيارية لحماية مفاتيح المزودين',
    'privacy.sharing.thirdParty.item3': 'يعمل شرح الذكاء الاصطناعي الاختياري على جهازك؛ يتم تنزيل ملفات النموذج فقط ويبقى ملخص القرار في متصفحك',
    'privacy.sharing.emergency.title': 'حالات الطوارئ:',
    'privacy.sharing.emergency.desc': 'لا يرسل هذا الإصدار سجل الموقع إلى خدمات الطوارئ أو شركاء الأبحاث.',
    'privacy.rights.title': 'حقوقك والتحكم',
    'privacy.rights.access.title': 'الوصول لبياناتك',
    'privacy.rights.access.desc': 'عرض سجل القرارات المحلي في لوحة المعلومات',
    'privacy.rights.export.title': 'تصدير بياناتك',
    'privacy.rights.export.desc': 'تحميل التفضيلات بصيغة JSON والسجل المحلي بصيغة CSV',
    'privacy.rights.delete.title': 'حذف بياناتك',
    'privacy.rights.delete.desc': 'مسح جميع البيانات المخزنة مؤقتاً وإعادة تعيين تفضيلاتك',
    'privacy.rights.analytics.title': 'التحكم في التحليلات',
    'privacy.rights.analytics.desc': 'تمكين أو تعطيل حفظ سجل القرارات المحلي مستقبلاً',
    'privacy.security.title': 'إجراءات الأمان',
    'privacy.security.desc': 'يقلل QuickER البيانات المحفوظة ويبقي مفاتيح المزودين خارج حزمة المتصفح:',
    'privacy.security.encryption.title': 'تشفير البيانات',
    'privacy.security.encryption.desc': 'جميع عمليات نقل البيانات مشفرة باستخدام بروتوكولات HTTPS/TLS',
    'privacy.security.storage.title': 'التخزين الآمن',
    'privacy.security.storage.desc': 'تُحفظ التفضيلات والملخصات في localStorage، بينما تبقى الإحداثيات الدقيقة في ذاكرة علامة التبويب المؤقتة فقط. لا يشفر QuickER بيانات المتصفح المحلية',
    'privacy.updates.title': 'تحديثات السياسة',
    'privacy.updates.desc': 'قد نحدث سياسة الخصوصية هذه لتعكس التغييرات في ممارساتنا أو المتطلبات القانونية. سنخطر المستخدمين بالتغييرات المهمة من خلال التطبيق.',
    'privacy.contact.title': 'تواصل معنا',
    'privacy.contact.desc': 'إذا كان لديك أسئلة حول سياسة الخصوصية هذه أو بياناتك:',
    'privacy.contact.email': 'البريد الإلكتروني:',
    'privacy.contact.address': 'تواصل المشروع:',
    'privacy.contact.addressLine': 'استخدم مستودع GitHub العام أو جهة اتصال مشاركة الهاكاثون.',
    'privacy.footer': '© ٢٠٢٦ نموذج QuickER للهاكاثون.',

    // Terms of Service
    'terms.backToSettings': 'العودة إلى الإعدادات',
    'terms.title': 'شروط الخدمة',
    'terms.lastUpdated': 'آخر تحديث:',
    'terms.acceptance.title': '١. قبول الشروط',
    'terms.acceptance.desc1': 'من خلال الوصول واستخدام QuickER ("التطبيق")، فإنك تقبل وتوافق على الالتزام بشروط وأحكام هذه الاتفاقية. إذا كنت لا توافق على الالتزام بما سبق، يرجى عدم استخدام هذه الخدمة.',
    'terms.acceptance.desc2': 'QuickER هو خدمة موقع الرعاية الصحية الطارئة المصممة لمساعدة المستخدمين في العثور على المستشفيات القريبة وخدمات الطوارئ. هذا التطبيق ليس بديلاً عن المشورة الطبية المهنية أو التشخيص أو العلاج.',
    'terms.medical.title': '٢. إخلاء المسؤولية الطبية',
    'terms.medical.important': 'إخلاء مسؤولية طبية مهم:',
    'terms.medical.disclaimer': 'QuickER ليس خدمة طبية ولا يقدم نصائح طبية. في حالة الطوارئ اتصل بخدمات الطوارئ المحلية فوراً، ولا تعتمد على هذا التطبيق وحده للرعاية الطارئة.',
    'terms.medical.desc': 'المعلومات التي يقدمها QuickER هي لأغراض إعلامية فقط ولا ينبغي اعتبارها كنصيحة طبية أو تشخيص أو توصيات علاجية. اطلب دائماً نصيحة طبيبك أو مقدم رعاية صحية مؤهل آخر مع أي أسئلة قد تكون لديك بخصوص حالة طبية.',
    'terms.license.title': '٣. رخصة الاستخدام',
    'terms.license.desc': 'يُمنح إذن لتحميل نسخة واحدة من QuickER مؤقتاً للاستخدام الشخصي غير التجاري المؤقت فقط. هذا منح رخصة وليس نقل ملكية، وتحت هذه الرخصة لا يمكنك:',
    'terms.license.item1': 'تعديل أو نسخ المواد',
    'terms.license.item2': 'استخدام المواد لأي غرض تجاري أو لأي عرض عام',
    'terms.license.item3': 'محاولة الهندسة العكسية لأي برمجيات موجودة في التطبيق',
    'terms.license.item4': 'إزالة أي حقوق طبع ونشر أو ملاحظات ملكية أخرى من المواد',
    'terms.responsibilities.title': '٤. مسؤوليات المستخدم',
    'terms.responsibilities.desc': 'باستخدام QuickER، فإنك توافق على:',
    'terms.responsibilities.item1': 'استخدام التطبيق فقط لأغراض قانونية ووفقاً لهذه الشروط',
    'terms.responsibilities.item2': 'تقديم معلومات موقع دقيقة عند استخدام خدمات الطوارئ',
    'terms.responsibilities.item3': 'عدم التدخل في أو تعطيل وظائف التطبيق',
    'terms.responsibilities.item4': 'عدم استخدام التطبيق لنقل محتوى ضار أو مسيء أو غير قانوني',
    'terms.responsibilities.item5': 'فهم أن بيانات الموقع قد لا تكون دقيقة ١٠٠٪ دائماً',
    'terms.privacy.title': '٥. الخصوصية وجمع البيانات',
    'terms.privacy.desc': 'خصوصيتك مهمة لنا. قد يجمع QuickER:',
    'terms.privacy.item1': 'بيانات الموقع لتقديم معلومات المستشفيات القريبة',
    'terms.privacy.item2': 'تحليلات الاستخدام لتحسين أداء التطبيق (إذا اخترت المشاركة)',
    'terms.privacy.item3': 'بيانات التفضيلات والإعدادات',
    'terms.privacy.policy': 'للحصول على معلومات تفصيلية حول كيفية جمعنا واستخدامنا وحماية بياناتك، يرجى مراجعة',
    'terms.availability.title': '٦. توفر الخدمة',
    'terms.availability.desc': 'يسعى QuickER لتقديم معلومات دقيقة ومحدثة حول مرافق الرعاية الصحية. ومع ذلك، لا يمكننا ضمان:',
    'terms.availability.item1': 'دقة ١٠٠٪ لمواقع المستشفيات أو معلومات الاتصال',
    'terms.availability.item2': 'التوفر الفوري للخدمات الطبية',
    'terms.availability.item3': 'توفر التطبيق المستمر دون انقطاع',
    'terms.availability.item4': 'أن جميع المستشفيات ستقبل تأمينك أو تقدم علاجات محددة',
    'terms.liability.title': '٧. تحديد المسؤولية',
    'terms.liability.desc': 'في أي حال من الأحوال لن يكون QuickER أو مورديه مسؤولون عن أي أضرار (بما في ذلك، دون حصر، الأضرار لفقدان البيانات أو الربح، أو بسبب انقطاع الأعمال) الناشئة عن استخدام أو عدم القدرة على استخدام QuickER، حتى لو تم إخطار QuickER أو ممثله المخول شفهياً أو كتابياً بإمكانية حدوث مثل هذا الضرر.',
    'terms.modifications.title': '٨. تعديل الشروط',
    'terms.modifications.desc': 'قد يراجع QuickER شروط الخدمة هذه في أي وقت دون إشعار. باستخدام هذا التطبيق، فإنك توافق على الالتزام بالإصدار الحالي من شروط الخدمة هذه. الاستمرار في استخدام التطبيق بعد نشر التغييرات يشكل قبولاً للشروط المعدلة.',
    'terms.governing.title': '٩. القانون الحاكم',
    'terms.governing.desc': 'تحكم هذه الشروط والأحكام وتفسر وفقاً للقوانين المحلية المعمول بها، وأنت تخضع بشكل لا رجعة فيه للاختصاص الحصري للمحاكم في تلك الولاية أو الموقع.',
    'terms.contact.title': '١٠. معلومات الاتصال',
    'terms.contact.desc': 'إذا كان لديك أي أسئلة حول شروط الخدمة هذه، يرجى الاتصال بنا من خلال',
    'terms.contact.about': 'صفحة حول التطبيق',
    'terms.contact.effective': 'هذه الشروط سارية اعتباراً من تاريخ آخر تحديث أعلاه وستبقى سارية باستثناء أي تغييرات في أحكامها في المستقبل، والتي ستكون سارية فوراً بعد نشرها على هذه الصفحة.',
    'terms.returnToSettings': 'العودة إلى الإعدادات'
  },
  fr: {
    // Header
    'nav.dashboard': 'Tableau de bord',
    'nav.about': 'À propos',
    'nav.settings': 'Paramètres',
    'btn.getStarted': 'Commencer',
    'btn.emergency': 'Urgence',

    // Bottom Navigation
    'nav.home': 'Accueil',
    'nav.options': 'Options',
    'nav.scenario': 'Scénario',

    // Hero Section
    'hero.title': 'Trouvez l\'hôpital le plus rapide maintenant',
    'hero.subtitle': 'Nous comparons les temps routiers et utilisons le trafic en direct uniquement si le fournisseur gratuit est disponible.',
    'btn.shareLocation': 'Partager ma position',
    'hero.loading': 'Calcul des données de trajet disponibles…',
    'hero.bestOption': 'Meilleure option',
    'hero.startNavigation': 'Démarrer la navigation',
    'hero.noHospitals': 'Aucun hôpital trouvé à proximité. Élargissez votre rayon de recherche dans les Options.',

    // Metrics
    'metrics.eta': 'ETA',
    'metrics.distance': 'km',
    'metrics.lowTraffic': 'Trafic fluide',
    'metrics.moderateTraffic': 'Trafic modéré',
    'metrics.heavyTraffic': 'Trafic dense',

    // Emergency Types
    'emergency.general': 'Urgences générales',
    'emergency.cardiac': 'Cardiaque',
    'emergency.pediatric': 'Pédiatrique',
    'emergency.maternity': 'Maternité',

    // Options Page
    'options.title': 'Options d\'urgence',
    'options.subtitle': 'Sélectionnez le type de soins dont vous avez besoin, et nous prioriserons ces établissements.',
    'options.emergencyType': 'Type d\'urgence',
    'options.searchRadius': 'Rayon de recherche (km)',
    'options.updateResults': 'Mettre à jour les résultats',
    'options.reachableAreas': 'Zones accessibles maintenant',
    'options.legend.5min': '5 min',
    'options.legend.10min': '10 min',
    'options.legend.15min': '15 min',

    // Dashboard
    'dashboard.title': 'Insights d\'accès aux urgences',
    'dashboard.subtitle': 'Temps moyen pour atteindre un hôpital, basé sur les données récentes',
    'dashboard.avgETA': 'ETA moyenne de la ville',
    'dashboard.peakHour': 'Heure de pointe',
    'dashboard.bestHour': 'Meilleure heure',
    'dashboard.noData': 'Les données apparaîtront lorsque vous utiliserez l\'application ou après l\'initialisation des données échantillons.',
    'dashboard.minutes': 'min',
    'dashboard.hour': 'Heure',
    'dashboard.area': 'Zone',
    'dashboard.avgTime': 'Temps moyen',

    // Settings
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Personnalisez votre expérience QuickER',
    'settings.language': 'Langue',
    'settings.interfaceLanguage': 'Langue de l\'interface',
    'settings.languageDesc': 'Choisissez votre langue préférée pour l\'application',
    'settings.emergencyPrefs': 'Préférences d\'urgence',
    'settings.defaultEmergencyType': 'Type d\'urgence par défaut',
    'settings.emergencyTypeDesc': 'Présélectionnez votre type d\'urgence le plus courant',
    'settings.privacyData': 'Confidentialité et données',
    'settings.analytics': 'Conserver l\'historique local',
    'settings.analyticsDesc': 'Conserver dans ce navigateur des résumés sans localisation pour le tableau de bord',
    'settings.clearCache': 'Effacer les données en cache',
    'settings.cacheDesc': 'Supprimer les sessions temporaires des pages, l\'historique local et les statuts de disponibilité de démonstration',
    'settings.exportData': 'Exporter vos données',
    'settings.exportDesc': 'Télécharger vos préférences actuelles (JSON)',
    'settings.legal': 'Légal et confidentialité',
    'settings.aboutApp': 'À propos de QuickER',
    'settings.privacyPolicy': 'Politique de confidentialité',
    'settings.termsOfService': 'Conditions d\'utilisation',
    'settings.version': 'v1.0.0',
    'settings.tagline': 'Le routage de soins d\'urgence simplifié',
    'settings.copyright': '© 2026 Prototype QuickER pour hackathon.',

    // Onboarding
    'onboarding.slide1.title': 'L\'hôpital adapté le plus rapide',
    'onboarding.slide1.desc': 'Comparez les hôpitaux par temps routier, avec le trafic en direct seulement si le fournisseur gratuit est disponible.',
    'onboarding.slide2.title': 'Filtres d\'urgence',
    'onboarding.slide2.desc': 'Filtrez les métadonnées publiques par type de soins, puis confirmez les services avec l\'établissement.',
    'onboarding.slide3.title': 'Vos données et votre confidentialité',
    'onboarding.slide3.desc': 'Nous utilisons votre position pour calculer les itinéraires. Les coordonnées précises restent uniquement dans la mémoire temporaire de l’onglet pendant la navigation et sont effacées au rechargement ou à la fermeture de l’onglet.',
    'onboarding.slide4.title': 'Activer l\'accès à la localisation',
    'onboarding.slide4.desc': 'Autorisez l\'accès à la localisation pour trouver les hôpitaux à proximité et calculer des itinéraires précis vers les soins d\'urgence.',
    'onboarding.slide5.title': 'Choisissez votre langue',
    'onboarding.slide5.desc': 'Sélectionnez votre langue préférée pour la meilleure expérience QuickER.',
    'onboarding.enableLocation': 'Activer la localisation',
    'onboarding.locationEnabled': 'Localisation activée',
    'onboarding.selectLanguage': 'Sélectionner la langue',
    'onboarding.back': 'Retour',
    'onboarding.next': 'Suivant',
    'onboarding.disclaimer': 'Cette application ne fournit pas de conseils médicaux.',
    'onboarding.privacyNotice': 'Les coordonnées précises restent uniquement dans la mémoire temporaire de l’onglet et sont effacées au rechargement ou à sa fermeture.',
    'onboarding.medicalDisclaimer': 'Appelez toujours les services d\'urgence pour les situations mettant la vie en danger.',
    'onboarding.getStarted': 'Commencer',

    // About
    'about.title': 'À propos de QuickER',
    'about.description': 'QuickER compare les hôpitaux selon le meilleur temps routier disponible et indique clairement si le trafic en direct facultatif est actif. Il ne remplace pas un avis médical ni les services d\'urgence.',
    'about.warning': 'Si vous êtes en danger immédiat, appelez les numéros d\'urgence locaux.',

    // Errors
    'error.permissionDenied': 'Nous ne pouvons pas trouver votre localisation. Activez la localisation dans votre navigateur ou choisissez un point de départ personnalisé.',
    'error.apiFailure': 'Données de trafic indisponibles. Affichage des temps estimés.',
    'error.offline': 'Vous êtes hors ligne. Nous réessaierons automatiquement.',
    'error.mapFailed': 'Échec du chargement de la carte. Réessayez ou changez de fournisseur.',

    // Toasts
    'toast.languageUpdated': 'Langue mise à jour',
    'toast.languageChanged': 'Langue de l\'interface changée en français.',
    'toast.emergencyTypeUpdated': 'Type d\'urgence par défaut mis à jour',
    'toast.preferenceSaved': 'Votre préférence a été sauvegardée.',
    'toast.analyticsEnabled': 'Analyses activées',
    'toast.analyticsDisabled': 'Analyses désactivées',
    'toast.analyticsEnabledDesc': 'Les prochains résumés seront conservés uniquement dans ce navigateur.',
    'toast.analyticsDisabledDesc': 'Les prochains résumés de décision ne seront pas enregistrés.',
    'toast.cacheCleared': 'Cache effacé',
    'toast.cacheClearedDesc': 'Les données en cache ont été supprimées. Vos préférences ont été préservées.',
    'toast.dataExported': 'Données exportées',
    'toast.dataExportedDesc': 'Vos données anonymisées ont été téléchargées.',

    // Buttons
    'btn.clearCache': 'Effacer le cache',
    'btn.exportData': 'Exporter les données',
    'btn.apply': 'Appliquer',

    // About Page
    'about.backToHome': 'Retour à l\'accueil',
    'about.badge': 'À propos de QuickER',
    'about.heroTitle': 'Le routage de soins d\'urgence simplifié',
    'about.heroSubtitle': 'Arrivez au bon hôpital, plus rapidement. Car en urgence, chaque minute compte.',
    'about.whatWeDo': 'Ce que nous faisons',
    'about.whatWeDoDesc1': 'QuickER compare les hôpitaux selon le meilleur temps routier disponible et indique clairement si le trafic en direct facultatif est actif. Il ne remplace pas un avis médical ni les services d\'urgence.',
    'about.whatWeDoDesc2': 'L\'application compare les temps routiers disponibles, les métadonnées publiques et les statuts de disponibilité de démonstration.',
    'about.whatWeDoDesc3': 'Nous agrégons les données de plusieurs sources pour vous assurer d\'obtenir les informations les plus précises et les plus récentes quand chaque minute compte.',
    'about.disclaimer': 'Avertissement important',
    'about.disclaimerTitle': 'Si vous êtes en danger immédiat ou vivez une urgence vitale, appelez immédiatement votre numéro d\'urgence local.',
    'about.disclaimerDesc': 'QuickER est un outil d\'assistance au routage et ne fournit pas de conseils médicaux, de diagnostic ou de recommandations de traitement. Consultez toujours des professionnels de santé qualifiés pour les décisions médicales.',
    'about.emergencyNumbers': 'Numéros d\'urgence',
    'about.howItWorks': 'Comment ça marche',
    'about.step1Title': '1. Détection de localisation',
    'about.step1Desc': 'Nous utilisons votre emplacement actuel pour trouver les établissements d\'urgence à proximité',
    'about.step2Title': '2. Analyse en temps réel',
    'about.step2Desc': 'Nous indiquons si chaque ETA utilise le trafic en direct, le réseau routier ou une estimation de distance',
    'about.step3Title': '3. Routage optimisé',
    'about.step3Desc': 'Obtenez l\'itinéraire le plus rapide vers l\'établissement de soins le plus approprié',
    'about.techPartners': 'Partenaires technologiques',
    'about.techPartnersDesc': 'QuickER est alimenté par des APIs et services leaders de l\'industrie :',
    'about.questionsTitle': 'Questions ou commentaires ?',
    'about.questionsDesc': 'Nous nous engageons à améliorer l\'accès aux soins d\'urgence pour tous.',
    'about.viewSettings': 'Voir les paramètres',
    'about.contactSupport': 'Contacter le support',

    // Dashboard Additional
    'dashboard.neighborhoodTimes': 'Temps d\'accès des quartiers',
    'dashboard.longestTimes': 'Zones avec les temps d\'accès les plus longs',
    'dashboard.exportData': 'Exporter les données',
    'dashboard.generateSample': 'Lancer la démo de réacheminement',
    'dashboard.last7Days': '7 derniers jours',
    'dashboard.avgETAByHour': 'ETA moyenne par',

    // Emergency Countries
    'emergency.countries.us': 'États-Unis',
    'emergency.countries.uk': 'Royaume-Uni',
    'emergency.countries.eu': 'Union Européenne',
    'emergency.countries.ca': 'Canada',
    'emergency.countries.au': 'Australie',
    'emergency.services.police': 'Police, Pompiers, Médical',
    'emergency.services.general': 'Services d\'urgence',

    // Privacy Policy
    'privacy.backToSettings': 'Retour aux paramètres',
    'privacy.title': 'Politique de confidentialité',
    'privacy.subtitle': 'Votre confidentialité et protection des données avec QuickER',
    'privacy.lastUpdated': 'Dernière mise à jour : juillet 2026',
    'privacy.introduction.title': 'Introduction',
    'privacy.introduction.desc1': 'Chez QuickER, nous nous engageons à protéger votre vie privée tout en fournissant des services de navigation d\'urgence essentiels. Cette politique de confidentialité explique comment nous collectons, utilisons et protégeons vos informations.',
    'privacy.introduction.desc2': 'Nous croyons que la transparence est cruciale, surtout lors du traitement de données de localisation sensibles pendant les situations d\'urgence.',
    'privacy.dataCollection.title': 'Informations que nous collectons',
    'privacy.dataCollection.location.title': 'Informations de localisation',
    'privacy.dataCollection.location.desc': 'Nous collectons vos données de localisation pour fournir des services de navigation :',
    'privacy.dataCollection.location.item1': 'Coordonnées GPS actuelles (uniquement avec votre autorisation)',
    'privacy.dataCollection.location.item2': 'Localisation approximative pour les calculs de trafic et de navigation',
    'privacy.dataCollection.location.item3': 'Préférences d\'itinéraire et sélections de destination',
    'privacy.dataCollection.usage.title': 'Analyses d\'utilisation',
    'privacy.dataCollection.usage.desc': 'Lorsque l\'historique local est activé, ce navigateur conserve :',
    'privacy.dataCollection.usage.item1': 'L\'heure, le filtre d\'urgence et le nombre de candidats',
    'privacy.dataCollection.usage.item2': 'L\'établissement recommandé, l\'ETA et sa source déclarée',
    'privacy.dataCollection.usage.item3': 'Le statut de démonstration, sans coordonnées précises',
    'privacy.dataCollection.preferences.title': 'Préférences de l\'application',
    'privacy.dataCollection.preferences.desc': 'Nous stockons vos paramètres localement sur votre appareil :',
    'privacy.dataCollection.preferences.item1': 'Préférences de langue et types d\'urgence par défaut',
    'privacy.dataCollection.preferences.item2': 'Rayon de recherche et préférences de notification',
    'privacy.dataCollection.preferences.item3': 'Statut d\'activation/désactivation des analyses',
    'privacy.dataUse.title': 'Comment nous utilisons vos informations',
    'privacy.dataUse.item1': 'Calculer les itinéraires avec le trafic disponible ou des estimations du réseau routier',
    'privacy.dataUse.item2': 'Fournir des temps d\'arrivée estimés et une navigation étape par étape',
    'privacy.dataUse.item3': 'Construire le tableau de bord avec des résumés conservés uniquement dans ce navigateur',
    'privacy.dataUse.item4': 'Mémoriser vos préférences pour les types d\'urgence et les paramètres de recherche',
    'privacy.dataUse.item5': 'Générer des informations sur l\'accessibilité des soins d\'urgence dans différentes zones',
    'privacy.location.title': 'Données de localisation et confidentialité',
    'privacy.location.important.title': 'Important : les coordonnées précises ne sont pas stockées de façon persistante',
    'privacy.location.important.desc': 'QuickER conserve les coordonnées précises uniquement dans la mémoire temporaire de l’onglet afin de préserver les résultats pendant la navigation. Elles disparaissent au rechargement ou à la fermeture de l’onglet et sont envoyées aux fournisseurs de carte et de routage nécessaires à votre demande.',
    'privacy.location.desc1': 'Votre position sert à trouver les hôpitaux, calculer les routes et tracer les isochrones facultatives. Elle n\'est pas ajoutée à l\'historique QuickER.',
    'privacy.location.desc2': 'La localisation est traitée dans votre navigateur, conservée temporairement pendant que cet onglet reste ouvert et envoyée directement aux fournisseurs de cartes ou de routage uniquement si nécessaire. Cette version ne crée pas d\'historique de déplacement côté serveur.',
    'privacy.location.controls.title': 'Vous contrôlez vos données de localisation :',
    'privacy.location.controls.item1': 'Accorder ou refuser l\'accès à la localisation via les paramètres de votre navigateur',
    'privacy.location.controls.item2': 'Effacer les données temporaires des pages et les données mises en cache via les paramètres de l\'application',
    'privacy.location.controls.item3': 'Désactiver complètement le partage de localisation (bien que cela limite les fonctionnalités)',
    'privacy.sharing.title': 'Partage de données et tiers',
    'privacy.sharing.desc': 'Nous minimisons le partage de données et ne travaillons qu\'avec des partenaires de confiance pour les services essentiels :',
    'privacy.sharing.thirdParty.title': 'Services tiers :',
    'privacy.sharing.thirdParty.item1': 'Fournisseurs de cartes et de navigation (pour les calculs de navigation)',
    'privacy.sharing.thirdParty.item2': 'Fonctions Cloudflare Pages facultatives protégeant les secrets des fournisseurs',
    'privacy.sharing.thirdParty.item3': 'L’explication IA facultative s’exécute sur votre appareil ; seuls les fichiers du modèle sont téléchargés et le résumé reste dans votre navigateur',
    'privacy.sharing.emergency.title': 'Situations d\'urgence :',
    'privacy.sharing.emergency.desc': 'Cette version ne transmet pas l\'historique de localisation aux services d\'urgence ni aux partenaires de recherche.',
    'privacy.rights.title': 'Vos droits et contrôle',
    'privacy.rights.access.title': 'Accéder à vos données',
    'privacy.rights.access.desc': 'Consulter l\'historique local dans le tableau de bord',
    'privacy.rights.export.title': 'Exporter vos données',
    'privacy.rights.export.desc': 'Télécharger les préférences en JSON et l\'historique local en CSV',
    'privacy.rights.delete.title': 'Supprimer vos données',
    'privacy.rights.delete.desc': 'Effacer toutes les données mises en cache et réinitialiser vos préférences',
    'privacy.rights.analytics.title': 'Contrôler les analyses',
    'privacy.rights.analytics.desc': 'Activer ou désactiver l\'enregistrement futur de l\'historique local',
    'privacy.security.title': 'Mesures de sécurité',
    'privacy.security.desc': 'QuickER réduit les données conservées et garde les secrets fournisseurs hors du navigateur :',
    'privacy.security.encryption.title': 'Chiffrement des données',
    'privacy.security.encryption.desc': 'Toute transmission de données est chiffrée en utilisant les protocoles HTTPS/TLS',
    'privacy.security.storage.title': 'Stockage sécurisé',
    'privacy.security.storage.desc': 'Les préférences et résumés utilisent localStorage ; les coordonnées précises utilisent uniquement la mémoire temporaire de l’onglet. Les données locales du navigateur ne sont pas chiffrées par QuickER',
    'privacy.updates.title': 'Mises à jour de la politique',
    'privacy.updates.desc': 'Nous pouvons mettre à jour cette politique de confidentialité pour refléter les changements dans nos pratiques ou les exigences légales. Nous informerons les utilisateurs des changements significatifs via l\'application.',
    'privacy.contact.title': 'Nous contacter',
    'privacy.contact.desc': 'Si vous avez des questions sur cette politique de confidentialité ou vos données :',
    'privacy.contact.email': 'Email :',
    'privacy.contact.address': 'Contact du projet :',
    'privacy.contact.addressLine': 'Utilisez le dépôt GitHub public ou le contact de la soumission au hackathon.',
    'privacy.footer': '© 2026 Prototype QuickER pour hackathon.',

    // Terms of Service
    'terms.backToSettings': 'Retour aux paramètres',
    'terms.title': 'Conditions d\'utilisation',
    'terms.lastUpdated': 'Dernière mise à jour :',
    'terms.acceptance.title': '1. Acceptation des conditions',
    'terms.acceptance.desc1': 'En accédant et en utilisant QuickER ("l\'Application"), vous acceptez et acceptez d\'être lié par les termes et dispositions de cet accord. Si vous n\'acceptez pas de respecter ce qui précède, veuillez ne pas utiliser ce service.',
    'terms.acceptance.desc2': 'QuickER est un service de localisation de soins de santé d\'urgence conçu pour aider les utilisateurs à trouver des hôpitaux et des services d\'urgence à proximité. Cette application n\'est pas un substitut aux conseils médicaux professionnels, au diagnostic ou au traitement.',
    'terms.medical.title': '2. Avertissement médical',
    'terms.medical.important': 'AVERTISSEMENT MÉDICAL IMPORTANT :',
    'terms.medical.disclaimer': 'QuickER n\'est PAS un service médical et ne fournit pas de conseils médicaux. En cas d\'urgence, contactez immédiatement vos services d\'urgence locaux. Ne comptez pas uniquement sur cette application.',
    'terms.medical.desc': 'Les informations fournies par QuickER sont à des fins informatives uniquement et ne doivent pas être considérées comme des conseils médicaux, un diagnostic ou des recommandations de traitement. Consultez toujours votre médecin ou un autre professionnel de santé qualifié pour toute question concernant une condition médicale.',
    'terms.license.title': '3. Licence d\'utilisation',
    'terms.license.desc': 'L\'autorisation est accordée de télécharger temporairement une copie de QuickER pour un usage personnel, non commercial et transitoire uniquement. Il s\'agit de l\'octroi d\'une licence, pas d\'un transfert de titre, et sous cette licence vous ne pouvez pas :',
    'terms.license.item1': 'modifier ou copier les matériaux',
    'terms.license.item2': 'utiliser les matériaux à des fins commerciales ou pour un affichage public',
    'terms.license.item3': 'tenter de faire de l\'ingénierie inverse sur tout logiciel contenu dans l\'application',
    'terms.license.item4': 'supprimer tout droit d\'auteur ou autres notations propriétaires des matériaux',
    'terms.responsibilities.title': '4. Responsabilités de l\'utilisateur',
    'terms.responsibilities.desc': 'En utilisant QuickER, vous acceptez de :',
    'terms.responsibilities.item1': 'Utiliser l\'application uniquement à des fins légales et conformément à ces Conditions',
    'terms.responsibilities.item2': 'Fournir des informations de localisation précises lors de l\'utilisation des services d\'urgence',
    'terms.responsibilities.item3': 'Ne pas interférer avec ou perturber la fonctionnalité de l\'application',
    'terms.responsibilities.item4': 'Ne pas utiliser l\'application pour transmettre du contenu nuisible, offensant ou illégal',
    'terms.responsibilities.item5': 'Comprendre que les données de localisation peuvent ne pas toujours être précises à 100%',
    'terms.privacy.title': '5. Confidentialité et collecte de données',
    'terms.privacy.desc': 'Votre confidentialité est importante pour nous. QuickER peut collecter :',
    'terms.privacy.item1': 'Données de localisation pour fournir des informations sur les hôpitaux à proximité',
    'terms.privacy.item2': 'Analyses d\'utilisation pour améliorer les performances de l\'application (si vous y consentez)',
    'terms.privacy.item3': 'Données de préférences et paramètres',
    'terms.privacy.policy': 'Pour des informations détaillées sur la façon dont nous collectons, utilisons et protégeons vos données, veuillez consulter notre',
    'terms.availability.title': '6. Disponibilité du service',
    'terms.availability.desc': 'QuickER s\'efforce de fournir des informations précises et à jour sur les établissements de soins de santé. Cependant, nous ne pouvons pas garantir :',
    'terms.availability.item1': 'Une précision de 100% des emplacements d\'hôpitaux ou des informations de contact',
    'terms.availability.item2': 'La disponibilité en temps réel des services médicaux',
    'terms.availability.item3': 'La disponibilité continue de l\'application sans interruptions',
    'terms.availability.item4': 'Que tous les hôpitaux accepteront votre assurance ou fourniront des traitements spécifiques',
    'terms.liability.title': '7. Limitation de responsabilité',
    'terms.liability.desc': 'En aucun cas QuickER ou ses fournisseurs ne seront responsables de tout dommage (y compris, sans limitation, les dommages pour perte de données ou de profit, ou dus à une interruption d\'activité) découlant de l\'utilisation ou de l\'incapacité d\'utiliser QuickER, même si QuickER ou son représentant autorisé a été notifié oralement ou par écrit de la possibilité de tels dommages.',
    'terms.modifications.title': '8. Modifications des conditions',
    'terms.modifications.desc': 'QuickER peut réviser ces conditions d\'utilisation à tout moment sans préavis. En utilisant cette application, vous acceptez d\'être lié par la version alors actuelle de ces conditions d\'utilisation. L\'utilisation continue de l\'application après la publication des modifications constitue une acceptation des conditions modifiées.',
    'terms.governing.title': '9. Loi applicable',
    'terms.governing.desc': 'Ces termes et conditions sont régis et interprétés conformément aux lois locales applicables, et vous vous soumettez irrévocablement à la juridiction exclusive des tribunaux de cet état ou lieu.',
    'terms.contact.title': '10. Informations de contact',
    'terms.contact.desc': 'Si vous avez des questions sur ces Conditions d\'utilisation, veuillez nous contacter via la',
    'terms.contact.about': 'page À propos',
    'terms.contact.effective': 'Ces conditions sont effectives à partir de la date de dernière mise à jour ci-dessus et resteront en vigueur sauf en ce qui concerne tout changement dans leurs dispositions à l\'avenir, qui sera en vigueur immédiatement après avoir été publié sur cette page.',
    'terms.returnToSettings': 'Retour aux paramètres'
  }
};
