// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loxfsvgepxcrocsqwrgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxveGZzdmdlcHhjcm9jc3F3cmdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzA2ODIsImV4cCI6MjA3MjY0NjY4Mn0.Ds2F_OSlC1usOaZzJvI1nyIBfjNl4QRe05W1wI39kiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});